---
- name: "Configuring Httpd server on Managed Nodes"
  hosts: webserver
  become: true
  tasks:
          - name: "Installing Httpd Software"
            package:
                    name: "httpd"
                    state: present
          - name: "Installing PHP Runtime"
            package:
                    name: "php"
                    state: present
          - name: "Deploying Web Pages"
            copy:
                    src: "webpages/"
                    dest: "/var/www/html/"
                    force: True
            notify: 
            - restart_httpd
          - name: "Starting Httpd webserver service"
            service:
                    name: "httpd"
                    state: started
                    enabled: True
  handlers:
          - name: restart_httpd
            service:
                    name: "httpd"
                    state: restarted
- name: "Configuring Haproxy Software on Managed Nodes"
  vars_files:
          - variable.yml
  hosts: loadbalancer
  become: True
  tasks:
          - name: "Installing Haproxy Software"
            package:
                    name: "haproxy"
                    state: present
          - name: "Deploying Dynamically updated haproxy.cfg"
            template:
                  src: "files/haproxy.cfg.j2"
                  dest: "/etc/haproxy/haproxy.cfg"
            notify: restart_haproxy
          - name: "Starting Haproxy Service"
            service:
                    name: "haproxy"
                    state: started
                    enabled: True
  handlers:
          - name: restart_haproxy
            service:
                    name: "haproxy"
                    state: restarted
